baseURL: "https://sgp2026.github.io/"
languageCode: en-us
title: SGP 2026 - Symposium on Geometry Processing 2026
theme: minimalConference
menu:
  main:
    - name: about
      url: /
      weight: 1
    - name: submit
      url: /submit/
      weight: 10
   #- name: program
   #  url: /program/
   #  weight: 20
    - name: registration
      url: /registration/ 
      weight: 30
    - name: venue
      url: /venue/
      weight: 40
    - name: organization
      url: /organization/
      weight: 50
   #- name: awards
   #  url: /awards/
   #  weight: 60
    - name: previous_sgps
      url: /past/
      weight: 70
Params:
  sponsorContact: "sgp2026-admin@list.inf.unibe.ch"
  submissionUrl: "https://srmv2.eg.org/COMFy/Conference/SGP_2026"
  events: 
    #- id: "conference_location"
    - id: "graduate_school"
      date: "June 29â€“30, 2026"
    - id: "conference"
      date: "July 01â€“03, 2026"
  sponsors:
    - name: ""
      id: "bronze"
      items:
        - name: "University of Bern"
          logo: "images/sponsors/ub_Logo_english_2019_RGB_ger.png"
    - name: "Software Award Sponsor"
      id: "bronze"
      items:
        - name: "GeometryFactory"
          logo: "images/sponsors/geometryfactory.png"
  importantDates:
   - id: abstract_submission
     date: "TBA"
   - id: paper_submission
     date: "TBA"
   - id: notification_of_acceptance
     date: "TBA"
   - id: revised_version_due
     date: "TBA"
   - id: camera_ready_due
     date: "TBA"
   - id: graduate_school
     date: "June 29â€“30, 2026"
   - id: conference
     date: "July 01â€“03, 2026"

#  - id: awards_chair
#    items: 
#      - name: "Marc Alexa"
#        email: "firstname.lastname at tu-berlin.de"
#        affiliation: "Technische UniversitÃ¤t Berlin"
  flagEmojis:
    Afghanistan: "ğŸ‡¦ğŸ‡«"
    Albania: "ğŸ‡¦ğŸ‡±"
    Algeria: "ğŸ‡©ğŸ‡¿"
    American Samoa: "ğŸ‡¦ğŸ‡¸"
    Andorra: "ğŸ‡¦ğŸ‡©"
    Angola: "ğŸ‡¦ğŸ‡´"
    Anguilla: "ğŸ‡¦ğŸ‡®"
    Antarctica: "ğŸ‡¦ğŸ‡¶"
    Antigua and Barbuda: "ğŸ‡¦ğŸ‡¬"
    Argentina: "ğŸ‡¦ğŸ‡·"
    Armenia: "ğŸ‡¦ğŸ‡²"
    Aruba: "ğŸ‡¦ğŸ‡¼"
    Australia: "ğŸ‡¦ğŸ‡º"
    Austria: "ğŸ‡¦ğŸ‡¹"
    Azerbaijan: "ğŸ‡¦ğŸ‡¿"
    Bahamas: "ğŸ‡§ğŸ‡¸"
    Bahrain: "ğŸ‡§ğŸ‡­"
    Bangladesh: "ğŸ‡§ğŸ‡©"
    Barbados: "ğŸ‡§ğŸ‡§"
    Belarus: "ğŸ‡§ğŸ‡¾"
    Belgium: "ğŸ‡§ğŸ‡ª"
    Belize: "ğŸ‡§ğŸ‡¿"
    Benin: "ğŸ‡§ğŸ‡¯"
    Bermuda: "ğŸ‡§ğŸ‡²"
    Bhutan: "ğŸ‡§ğŸ‡¹"
    Bolivia: "ğŸ‡§ğŸ‡´"
    Bonaire, Sint Eustatius and Saba: "ğŸ‡§ğŸ‡¶"
    Bosnia and Herzegovina: "ğŸ‡§ğŸ‡¦"
    Botswana: "ğŸ‡§ğŸ‡¼"
    Bouvet Island: "ğŸ‡§ğŸ‡»"
    Brazil: "ğŸ‡§ğŸ‡·"
    British Indian Ocean Territory: "ğŸ‡®ğŸ‡´"
    Brunei Darussalam: "ğŸ‡§ğŸ‡³"
    Bulgaria: "ğŸ‡§ğŸ‡¬"
    Burkina Faso: "ğŸ‡§ğŸ‡«"
    Burundi: "ğŸ‡§ğŸ‡®"
    Cambodia: "ğŸ‡°ğŸ‡­"
    Cameroon: "ğŸ‡¨ğŸ‡²"
    Canada: "ğŸ‡¨ğŸ‡¦"
    Cape Verde: "ğŸ‡¨ğŸ‡»"
    Cayman Islands: "ğŸ‡°ğŸ‡¾"
    Central African Republic: "ğŸ‡¨ğŸ‡«"
    Chad: "ğŸ‡¹ğŸ‡©"
    Chile: "ğŸ‡¨ğŸ‡±"
    China: "ğŸ‡¨ğŸ‡³"
    Christmas Island: "ğŸ‡¨ğŸ‡½"
    Cocos (Keeling) Islands: "ğŸ‡¨ğŸ‡¨"
    Colombia: "ğŸ‡¨ğŸ‡´"
    Comoros: "ğŸ‡°ğŸ‡²"
    Congo: "ğŸ‡¨ğŸ‡©"
    Congo: "ğŸ‡¨ğŸ‡¬"
    Cook Islands: "ğŸ‡¨ğŸ‡°"
    Costa Rica: "ğŸ‡¨ğŸ‡·"
    Croatia: "ğŸ‡­ğŸ‡·"
    Cuba: "ğŸ‡¨ğŸ‡º"
    CuraÃ§ao: "ğŸ‡¨ğŸ‡¼"
    Cyprus: "ğŸ‡¨ğŸ‡¾"
    Czech Republic: "ğŸ‡¨ğŸ‡¿"
    CÃ´te D'Ivoire: "ğŸ‡¨ğŸ‡®"
    Denmark: "ğŸ‡©ğŸ‡°"
    Djibouti: "ğŸ‡©ğŸ‡¯"
    Dominica: "ğŸ‡©ğŸ‡²"
    Dominican Republic: "ğŸ‡©ğŸ‡´"
    Ecuador: "ğŸ‡ªğŸ‡¨"
    Egypt: "ğŸ‡ªğŸ‡¬"
    El Salvador: "ğŸ‡¸ğŸ‡»"
    Equatorial Guinea: "ğŸ‡¬ğŸ‡¶"
    Eritrea: "ğŸ‡ªğŸ‡·"
    Estonia: "ğŸ‡ªğŸ‡ª"
    Ethiopia: "ğŸ‡ªğŸ‡¹"
    Falkland Islands (Malvinas): "ğŸ‡«ğŸ‡°"
    Faroe Islands: "ğŸ‡«ğŸ‡´"
    Fiji: "ğŸ‡«ğŸ‡¯"
    Finland: "ğŸ‡«ğŸ‡®"
    France: "ğŸ‡«ğŸ‡·"
    French Guiana: "ğŸ‡¬ğŸ‡«"
    French Polynesia: "ğŸ‡µğŸ‡«"
    French Southern Territories: "ğŸ‡¹ğŸ‡«"
    Gabon: "ğŸ‡¬ğŸ‡¦"
    Gambia: "ğŸ‡¬ğŸ‡²"
    Georgia: "ğŸ‡¬ğŸ‡ª"
    Germany: "ğŸ‡©ğŸ‡ª"
    Ghana: "ğŸ‡¬ğŸ‡­"
    Gibraltar: "ğŸ‡¬ğŸ‡®"
    Greece: "ğŸ‡¬ğŸ‡·"
    Greenland: "ğŸ‡¬ğŸ‡±"
    Grenada: "ğŸ‡¬ğŸ‡©"
    Guadeloupe: "ğŸ‡¬ğŸ‡µ"
    Guam: "ğŸ‡¬ğŸ‡º"
    Guatemala: "ğŸ‡¬ğŸ‡¹"
    Guernsey: "ğŸ‡¬ğŸ‡¬"
    Guinea-Bissau: "ğŸ‡¬ğŸ‡¼"
    Guinea: "ğŸ‡¬ğŸ‡³"
    Guyana: "ğŸ‡¬ğŸ‡¾"
    Haiti: "ğŸ‡­ğŸ‡¹"
    Heard Island and Mcdonald Islands: "ğŸ‡­ğŸ‡²"
    Honduras: "ğŸ‡­ğŸ‡³"
    Hong Kong: "ğŸ‡­ğŸ‡°"
    Hungary: "ğŸ‡­ğŸ‡º"
    Iceland: "ğŸ‡®ğŸ‡¸"
    India: "ğŸ‡®ğŸ‡³"
    Indonesia: "ğŸ‡®ğŸ‡©"
    Iran: "ğŸ‡®ğŸ‡·"
    Iraq: "ğŸ‡®ğŸ‡¶"
    Ireland: "ğŸ‡®ğŸ‡ª"
    Isle of Man: "ğŸ‡®ğŸ‡²"
    Israel: "ğŸ‡®ğŸ‡±"
    Italy: "ğŸ‡®ğŸ‡¹"
    Jamaica: "ğŸ‡¯ğŸ‡²"
    Japan: "ğŸ‡¯ğŸ‡µ"
    Jersey: "ğŸ‡¯ğŸ‡ª"
    Jordan: "ğŸ‡¯ğŸ‡´"
    Kazakhstan: "ğŸ‡°ğŸ‡¿"
    Kenya: "ğŸ‡°ğŸ‡ª"
    Kiribati: "ğŸ‡°ğŸ‡®"
    Kuwait: "ğŸ‡°ğŸ‡¼"
    Kyrgyzstan: "ğŸ‡°ğŸ‡¬"
    Lao People's Democratic Republic: "ğŸ‡±ğŸ‡¦"
    Latvia: "ğŸ‡±ğŸ‡»"
    Lebanon: "ğŸ‡±ğŸ‡§"
    Lesotho: "ğŸ‡±ğŸ‡¸"
    Liberia: "ğŸ‡±ğŸ‡·"
    Libya: "ğŸ‡±ğŸ‡¾"
    Liechtenstein: "ğŸ‡±ğŸ‡®"
    Lithuania: "ğŸ‡±ğŸ‡¹"
    Luxembourg: "ğŸ‡±ğŸ‡º"
    Macao: "ğŸ‡²ğŸ‡´"
    Macedonia: "ğŸ‡²ğŸ‡°"
    Madagascar: "ğŸ‡²ğŸ‡¬"
    Malawi: "ğŸ‡²ğŸ‡¼"
    Malaysia: "ğŸ‡²ğŸ‡¾"
    Maldives: "ğŸ‡²ğŸ‡»"
    Mali: "ğŸ‡²ğŸ‡±"
    Malta: "ğŸ‡²ğŸ‡¹"
    Marshall Islands: "ğŸ‡²ğŸ‡­"
    Martinique: "ğŸ‡²ğŸ‡¶"
    Mauritania: "ğŸ‡²ğŸ‡·"
    Mauritius: "ğŸ‡²ğŸ‡º"
    Mayotte: "ğŸ‡¾ğŸ‡¹"
    Mexico: "ğŸ‡²ğŸ‡½"
    Micronesia: "ğŸ‡«ğŸ‡²"
    Moldova: "ğŸ‡²ğŸ‡©"
    Monaco: "ğŸ‡²ğŸ‡¨"
    Mongolia: "ğŸ‡²ğŸ‡³"
    Montenegro: "ğŸ‡²ğŸ‡ª"
    Montserrat: "ğŸ‡²ğŸ‡¸"
    Morocco: "ğŸ‡²ğŸ‡¦"
    Mozambique: "ğŸ‡²ğŸ‡¿"
    Myanmar: "ğŸ‡²ğŸ‡²"
    Namibia: "ğŸ‡³ğŸ‡¦"
    Nauru: "ğŸ‡³ğŸ‡·"
    Nepal: "ğŸ‡³ğŸ‡µ"
    The Netherlands: "ğŸ‡³ğŸ‡±"
    New Caledonia: "ğŸ‡³ğŸ‡¨"
    New Zealand: "ğŸ‡³ğŸ‡¿"
    Nicaragua: "ğŸ‡³ğŸ‡®"
    Niger: "ğŸ‡³ğŸ‡ª "
    Nigeria: "ğŸ‡³ğŸ‡¬"
    Niue: "ğŸ‡³ğŸ‡º"
    Norfolk Island: "ğŸ‡³ğŸ‡«"
    North Korea: "ğŸ‡°ğŸ‡µ"
    Northern Mariana Islands: "ğŸ‡²ğŸ‡µ"
    Norway: "ğŸ‡³ğŸ‡´"
    Oman: "ğŸ‡´ğŸ‡²"
    Pakistan: "ğŸ‡µğŸ‡°"
    Palau: "ğŸ‡µğŸ‡¼"
    Palestinian Territory: "ğŸ‡µğŸ‡¸"
    Panama: "ğŸ‡µğŸ‡¦"
    Papua New Guinea: "ğŸ‡µğŸ‡¬"
    Paraguay: "ğŸ‡µğŸ‡¾"
    Peru: "ğŸ‡µğŸ‡ª"
    Philippines: "ğŸ‡µğŸ‡­"
    Pitcairn: "ğŸ‡µğŸ‡³"
    Poland: "ğŸ‡µğŸ‡±"
    Portugal: "ğŸ‡µğŸ‡¹"
    Puerto Rico: "ğŸ‡µğŸ‡·"
    Qatar: "ğŸ‡¶ğŸ‡¦"
    Romania: "ğŸ‡·ğŸ‡´"
    Russia: "ğŸ‡·ğŸ‡º"
    Rwanda: "ğŸ‡·ğŸ‡¼"
    RÃ©union: "ğŸ‡·ğŸ‡ª"
    Saint BarthÃ©lemy: "ğŸ‡§ğŸ‡±"
    Saint Helena, Ascension and Tristan Da Cunha: "ğŸ‡¸ğŸ‡­"
    Saint Kitts and Nevis: "ğŸ‡°ğŸ‡³"
    Saint Lucia: "ğŸ‡±ğŸ‡¨"
    Saint Martin (French Part): "ğŸ‡²ğŸ‡«"
    Saint Pierre and Miquelon: "ğŸ‡µğŸ‡²"
    Saint Vincent and The Grenadines: "ğŸ‡»ğŸ‡¨"
    Samoa: "ğŸ‡¼ğŸ‡¸"
    San Marino: "ğŸ‡¸ğŸ‡²"
    Sao Tome and Principe: "ğŸ‡¸ğŸ‡¹"
    Saudi Arabia: "ğŸ‡¸ğŸ‡¦"
    Senegal: "ğŸ‡¸ğŸ‡³"
    Serbia: "ğŸ‡·ğŸ‡¸"
    Seychelles: "ğŸ‡¸ğŸ‡¨"
    Sierra Leone: "ğŸ‡¸ğŸ‡±"
    Singapore: "ğŸ‡¸ğŸ‡¬"
    Sint Maarten (Dutch Part): "ğŸ‡¸ğŸ‡½"
    Slovakia: "ğŸ‡¸ğŸ‡°"
    Slovenia: "ğŸ‡¸ğŸ‡®"
    Solomon Islands: "ğŸ‡¸ğŸ‡§"
    Somalia: "ğŸ‡¸ğŸ‡´"
    South Africa: "ğŸ‡¿ğŸ‡¦"
    South Georgia: "ğŸ‡¬ğŸ‡¸"
    South Korea: "ğŸ‡°ğŸ‡·"
    South Sudan: "ğŸ‡¸ğŸ‡¸"
    Spain: "ğŸ‡ªğŸ‡¸"
    Sri Lanka: "ğŸ‡±ğŸ‡°"
    Sudan: "ğŸ‡¸ğŸ‡©"
    Suriname: "ğŸ‡¸ğŸ‡·"
    Svalbard and Jan Mayen: "ğŸ‡¸ğŸ‡¯"
    Swaziland: "ğŸ‡¸ğŸ‡¿"
    Sweden: "ğŸ‡¸ğŸ‡ª"
    Switzerland: "ğŸ‡¨ğŸ‡­"
    Syrian Arab Republic: "ğŸ‡¸ğŸ‡¾"
    Taiwan: "ğŸ‡¹ğŸ‡¼"
    Tajikistan: "ğŸ‡¹ğŸ‡¯"
    Tanzania: "ğŸ‡¹ğŸ‡¿"
    Thailand: "ğŸ‡¹ğŸ‡­"
    Timor-Leste: "ğŸ‡¹ğŸ‡±"
    Togo: "ğŸ‡¹ğŸ‡¬"
    Tokelau: "ğŸ‡¹ğŸ‡°"
    Tonga: "ğŸ‡¹ğŸ‡´"
    Trinidad and Tobago: "ğŸ‡¹ğŸ‡¹"
    Tunisia: "ğŸ‡¹ğŸ‡³"
    Turkey: "ğŸ‡¹ğŸ‡·"
    Turkmenistan: "ğŸ‡¹ğŸ‡²"
    Turks and Caicos Islands: "ğŸ‡¹ğŸ‡¨"
    Tuvalu: "ğŸ‡¹ğŸ‡»"
    Uganda: "ğŸ‡ºğŸ‡¬"
    Ukraine: "ğŸ‡ºğŸ‡¦"
    United Arab Emirates: "ğŸ‡¦ğŸ‡ª"
    UK: "ğŸ‡¬ğŸ‡§"
    United States Minor Outlying Islands: "ğŸ‡ºğŸ‡²"
    USA: "ğŸ‡ºğŸ‡¸"
    Uruguay: "ğŸ‡ºğŸ‡¾"
    Uzbekistan: "ğŸ‡ºğŸ‡¿"
    Vanuatu: "ğŸ‡»ğŸ‡º"
    Vatican City: "ğŸ‡»ğŸ‡¦"
    Venezuela: "ğŸ‡»ğŸ‡ª"
    Viet Nam: "ğŸ‡»ğŸ‡³"
    Virgin Islands, British: "ğŸ‡»ğŸ‡¬"
    Virgin Islands, U.S.: "ğŸ‡»ğŸ‡®"
    Wallis and Futuna: "ğŸ‡¼ğŸ‡«"
    Western Sahara: "ğŸ‡ªğŸ‡­"
    Yemen: "ğŸ‡¾ğŸ‡ª"
    Zambia: "ğŸ‡¿ğŸ‡²"
    Zimbabwe: "ğŸ‡¿ğŸ‡¼"
    Ã…land Islands: "ğŸ‡¦ğŸ‡½"
