#baseURL: "https://sgp2026.github.io/"
baseURL: "https://tmp.cgg.unibe.ch/sgp26-v2/"
languageCode: en-us
title: SGP 2026 - Symposium on Geometry Processing 2026
theme: minimalConference
menu:
  main:
    - name: about
      url: /
      weight: 1
    - name: submit
      url: /submit/
      weight: 10
   #- name: program
   #  url: /program/
   #  weight: 20
    - name: registration
      url: /registration/ 
      weight: 30
    - name: venue
      url: /venue/
      weight: 40
    - name: organization
      url: /organization/
      weight: 50
   #- name: awards
   #  url: /awards/
   #  weight: 60
    - name: previous_sgps
      url: /past/
      weight: 70
Params:
  sponsorContact: "sgp2026-admin@list.inf.unibe.ch"
  submissionUrl: "https://srmv2.eg.org/COMFy/Conference/SGP_2026"
  events: 
    #- id: "conference_location"
    - id: "graduate_school"
      date: "June 29 – 30, 2026"
    - id: "conference"
      date: "July 01 – 03, 2026"
  sponsors:
    - name: ""
      id: "bronze"
      items:
        - name: "University of Bern"
          logo: "images/sponsors/ub_Logo_english_2019_RGB_ger.png"
    - name: "Software Award Sponsor"
      id: "bronze"
      items:
        - name: "GeometryFactory"
          logo: "images/sponsors/geometryfactory.png"
  importantDates:
   - id: abstract_submission
     date: "TBA"
   - id: paper_submission
     date: "TBA"
   - id: notification_of_acceptance
     date: "TBA"
   - id: revised_version_due
     date: "TBA"
   - id: camera_ready_due
     date: "TBA"
   - id: graduate_school
     date: "June 29–30, 2026"
   - id: conference
     date: "July 01–03, 2026"

#  - id: awards_chair
#    items: 
#      - name: "Marc Alexa"
#        email: "firstname.lastname at tu-berlin.de"
#        affiliation: "Technische Universität Berlin"
