#baseURL: "https://sgp2026.github.io/"
baseURL: "https://tmp.cgg.unibe.ch/sgp26-v3/"
languageCode: en-us
title: SGP 2026 - Symposium on Geometry Processing 2026
theme: minimalConference
module:
  imports:
  - path: github.com/future-wd/hugo-responsive-images
params:
  image:
    widths: [600, 900, 1300] # widths to generate if widths not specified
    # shortcode_widths: [600, 900, 1300] # custom widths for shortcode use in markdown files. If unset defaults to widths
    # render_hook_widths: [600, 900, 1300] # custom widths for render hook use in markdown files. If unset defaults to shortcode widths
    densities: [1,2] # densities which are output when an image width is specified
    formats: [webp, original] # set output formats. options are `original`, `bmp`, `gif`, `jpeg`, `jpg`, `png`, `tif`, `tiff`, and `webp`. In order of least supported to most supported. For "image_only" the first format will be used.
    class: img-fluid # default image class if no class is specified
    figure_class: "figure img-fluid" # default figure class
    figure_image_class: "figure-img img-fluid" # default figure image class (appended to image class) ## USE .class to override outside of config
    figcaption_class: figure-caption # default figcaption class
    figcaption_title_h: 4 # heading level for figure title
    render_hook_wrapper_class: img-wrapper # image wrapper class for render hook
    shortcode_wrapper_class: img-wrapper # image wrapper class for shortcode
    loading: lazy # or auto/lazysizes # lazy/auto are for stock browser behavior, lazysizes will use lazysizes.js
    render_hook: false # set to false to disable included markdown image render hook
                      # override by setting imageRenderHook: true/false in front matter
    output: partial # img, figure # partial called by render-hook
    # placeholder: lqip # or dominant/file_name  (see colours set up in assets/images/placeholder-colors) use filename without .gif
    lqip_blur_amount: 5 # apply gaussian blur amount of 5 to lqip
                      # may need to be increased at a page level for larger images
    lqip_div_amount: 5 # lqip is 5x smaller than the smallest image in srcset
    gif_div_amount: 10 # single color gif placeholder is 10x smaller than smallest image in srcset
    # provider: netlify # currently only supports netlify image processing.
    suppress_width_warning: false # turn of warning that image cannot be resized to the widths specified


menu:
  main:
    - name: about
      url: /
      weight: 1
    - name: submit
      url: /submit/
      weight: 10
   #- name: program
   #  url: /program/
   #  weight: 20
    - name: registration
      url: /registration/ 
      weight: 30
    - name: venue
      url: /venue/
      weight: 40
    - name: organization
      url: /organization/
      weight: 50
   #- name: awards
   #  url: /awards/
   #  weight: 60
    - name: previous_sgps
      url: /past/
      weight: 70
Params:
  sponsorContact: "sgp2026-admin@list.inf.unibe.ch"
  submissionUrl: "https://srmv2.eg.org/COMFy/Conference/SGP_2026"
  events: 
    #- id: "conference_location"
    - id: "graduate_school"
      date: "June 29 – 30, 2026"
    - id: "conference"
      date: "July 01 – 03, 2026"
  sponsors:
    - name: ""
      id: "bronze"
      items:
        - name: "University of Bern"
          logo: "images/sponsors/ub_Logo_english_2019_RGB_ger.png"
    - name: "Software Award Sponsor"
      id: "bronze"
      items:
        - name: "GeometryFactory"
          logo: "images/sponsors/geometryfactory.png"
  importantDates:
    round_one:
      - id: abstract_submission
        date: "Feb 02"
      - id: paper_submission
        date: "Feb 04"
      - id: notification_of_acceptance
        date: "Mar 16"
      - id: revised_version_due
        date: "Mar 26"
      - id: camera_ready_due
        date: "Apr 2"
    round_two:
      - id: abstract_submission2
        date: "Apr 13"
      - id: paper_submission2
        date: "Apr 15"
      - id: notification_of_acceptance2
        date: "May 25"
      - id: revised_version_due2
        date: "Jun 04"
      - id: camera_ready_due2
        date: "Jun 11"

#  - id: awards_chair
#    items: 
#      - name: "Marc Alexa"
#        email: "firstname.lastname at tu-berlin.de"
#        affiliation: "Technische Universität Berlin"
